CollaboratingPlatypus/PetaPoco

- PetaPoco/Models/Generated/PetaPoco.Core.ttinclude
Nullable columns, and correctly handle DataScale of 0 for number columns.
Resolves #187 Oracle nullable columns.
> OracleSchemaReader fixes, closes #187

- PetaPoco/Database.cs
If SqlCommand.ExecuteScalar() returns DBNull.Value and the return type T of ExecuteScalar<T> is nullable, an InvalidCastException is thrown.
This patch handles DBNull.Value the same way as null.
This happens for example if ExecuteScalar<int?>("SELECT MAX(id) FROM empty_table") is queried on an empty table.
> Added support for DBNull in ExecuteScalar

- PetaPoco/Core/PocoData.cs
This is a proposed fix for #261 . I believe this to be a regression, given that other versions of PetaPoco I've used have been capable of populating internal types
> Fixes issue where internal properties aren't populated

- PetaPoco/Database.cs
If your enum is based on byte type, peta poco fails on casting. JCKodel's solution works well, 
https://github.com/CollaboratingPlatypus/PetaPoco/issues/126
> Fixing byte based enums

- PetaPoco/T4 Templates/Database.tt
- PetaPoco/T4 Templates/PetaPoco.Core.ttinclude
This is a simple addition of a Exclude by Prefix variable that can be used to supress a block of tables from being generated.  
It may work better to add this as a Regex instead but the above was all my project neeed.
Eg: 
``ExcludeTablesRegex = "^(cms|CMS|umbraco).*$";``
Or maybe even a ovverride to included only matched tables instead of defaulting to all.
``IncludeTablesRegex = "myPrefix.*";``
> Pynej patch 1

- PetaPoco/T4 Templates/PetaPoco.Core.ttinclude
Fixed auto-increment for Guid key when its default value is set in SQL server as newsequentialid() or newid().
Here is the case:
Insert a record into a table with primary key is Guid and its default value is newsquentialid() or newid().
Fix for the issue #305
> Update PetaPoco.Core.ttinclude to support Guid auto-generation in SQL

- PetaPoco/T4 Templates/PetaPoco.Core.ttinclude
Addresses issue #362 by changing `GetCurrentProject()`, `GetProjectPath()`, `GetDataDirectory()`, and `GetConfigPath()` methods  to detect if `EnvDTE.Project` is `null` (which happens if transformation happens outside of Visual Studio) and using alternative means of getting their information.
This makes PetaPoco's templates compatible with [TextTransform.exe](https://msdn.microsoft.com/en-us/library/bb126245.aspx) and [TransformOnBuild](https://github.com/clariuslabs/TransformOnBuild) NuGet package.
> Allow transformation of T4 template outside of Visual Studio

- PetaPoco/Core/DatabaseProvider.cs
- PetaPoco/Database.cs
- PetaPoco/Providers/FirebirdDbDatabaseProvider.cs
- PetaPoco/Providers/MsAccessDbDatabaseProvider.cs
- PetaPoco/Providers/OracleDatabaseProvider.cs
- PetaPoco/Providers/PostgreSQLDatabaseProvider.cs
- PetaPoco/Providers/SQLiteDatabaseProvider.cs
- PetaPoco/Providers/SqlServerCEDatabaseProviders.cs
- PetaPoco/Providers/SqlServerDatabaseProvider.cs
`Database` has two helper methods which are marked `internal` and which are only called by `DatabaseProvider` and descendants. Because they are `internal`, they cannot be called by `DatabaseProvider` descendants in other assemblies.  Move these helper methods to `DatabaseProvider` and mark as `protected`.
Addresses #428
> Move Database helper methods to DatabaseProvider

- PetaPoco/Database.cs
- PetaPoco/IQuery.cs
A simple addition. Expanded multi-poco query and fetch to support 5 poco types, up from the previous 4.
The company I work for currently uses an edited version of PetaPoco with these added, but it would be nice to have this functionality added to the official version.
> Added support for queries and fetches that include five poco types

- PetaPoco/Core/ConventionMapper.cs
Support for value converter attribute in #408 appears to be missing two null checks in code added to `ConventionMapper.cs`. This was causing queries into `dynamic` objects to throw an exception, as reported in #415 and #430.
I added the null checks, and the examples in the referenced issues work fine now. All existing unit tests also pass. Possibly some further testing is needed before releasing.
> Null check in FromDbConverter and ToDbConverter

- PetaPoco/DatabaseConfigurationExtensions.cs
The overload of `UsingProvider()` that takes a provider instance and a configuration callback does not actually use the callback.
> Add missing provider configuration step

- PetaPoco.Tests.Unit/PetaPoco.Tests.Unit.csproj
- PetaPoco.Tests.Unit/Providers/CustomProviderRegistrationTests.cs
- PetaPoco.sln.DotSettings
- PetaPoco/Core/DatabaseProvider.cs
Addresses #447 
This is a first pass at the sort of thing I had in mind; I'm interested to hear feedback. What I'm envisioning is that rather than the end user needing to know how to correctly register a custom provider (i.e., what initialStrings to use), the provider could just implement its own static `Register()` method to do the work.
It is intentional that you can register more than one string for a provider. This is because one custom provider I'm working on for a third-party database has a provider name of `Foo.Data.Provider`, but the other types are called `BarConnection` and `BarFactory`.
I was also thinking about a more complicated and more powerful solution, but it would require a breaking change (new method on `IProvider`).
> Add methods to register and retrieve custom providers

- PetaPoco/Database.cs
One of the constructors for `Database` is `public Database(string connectionString, string providerName = null)`
However, if `providerName` is actually omitted and only one string parameter is given, the constructor that winds up being called is `public Database(string connectionStringName)`. In other words, there is no way to call the first overload above without also specifying a provider name. 
So I think the `providerName` parameter should be made mandatory, to avoid any misunderstandings. If this PR gets merged, I'll also update the docs.
> Make providerName required for constructor overload

- PetaPoco/Database.cs
//The primary key is not using the save method when the self identification column is added.   
Examples:
[TableName("dbo.Person")]
[PrimaryKey("IdCard", AutoIncrement = false)]
[ExplicitColumns]
class Person
{
[Column] public string IdCard { get; set; }
[Column] public string Name { get; set; }
}
var model = new Person() { IdCard = "1234567890", Name = "mayb" };
var db = new Database();
if (db.Exists<Person>(model)) db.Update(model);
else db.Insert(model);
> Exists Parameter support entity objects

- PetaPoco.Tests.Unit/Core/PocoDataTests.cs
- PetaPoco/Attributes/ResultColumnAttribute.cs
- PetaPoco/Core/ColumnInfo.cs
- PetaPoco/Core/ConventionMapper.cs
- PetaPoco/Core/PocoColumn.cs
- PetaPoco/Core/PocoData.cs
I decided to implement this with an enum instead of a bool param in the constructor -- `ResultColumn(false)` just looked too much like it was saying that the field is _not_ a result column.
In `ColumnInfo` and `PocoColumn`, I called the field `AutoSelectedResultColumn`, because keeping the name as `IncludeInAutoSelect` made its purpose sound too broad.
> Include result column in auto select

- PetaPoco/Database.cs
- PetaPoco/IQuery.cs
Give Fetch(), Query(), Page(), and SkipTake() overloads that omit the
string sql parameter, so that PetaPoco will do SELECT *
It didn't seem to make sense to add overloads for the multi-poco versions, so I just did the base versions.
> Add overloads without sql param

- PetaPoco.Tests.Unit/Core/SqlTests.cs
- PetaPoco/Core/Sql.cs
Long story short, I think this functionality should be removed.
I didn't think through all of the implications; I got the parameter onto the `Sql` object but didn't pay attention to what would happen in `CreateCommand()`, `ProcessQueryParams()` and `AddParam()`. So currently the scenario envisioned in #488 only works if `EnableNamedParameters == false` and the placeholder in `Join()` is `@@0`. Any other combination fails, for one reason or another. I consider these conditions too narrow to count as a success.
There could be more work done to get all parts of this to work, but it's a longer and more invasive procedure, and personally I'm not sure it's worth it. There are a few viable workarounds for the original reported issue, and I think it should just be left at that.
> Remove AddParameter()

- PetaPoco.Tests.Unit/DatabaseTests.cs
- PetaPoco/Database.cs
When I've been writing little tests for things in LinqPad, I've been using the `Database` constructor that takes a connection string and a provider name, and I've been a little frustrated that I can't always remember the exact name/spelling of a provider. I know that I could use `nameof(SqlServerDatabaseProvider)` to get help from Intellisense, but I thought it would be simpler and more idiomatic if I could just do `new Database<SqlServerDatabaseProvider>(connString)`.
While I was in there, I made sure that all `Database` constructors have the optional `IMapper` parameter, because I couldn't see why some had it and some didn't.
> Add generic db constructor, and add optional mapper to all

- PetaPoco.Tests.Unit/DatabaseConfigurationTests.cs
- PetaPoco.Tests.Unit/DatabaseTests.cs
- PetaPoco/Database.cs
There was something missing with #499 -- if you pass in a connection, you could also pass in a provider type, to override what the connection wants to use, but you couldn't pass in a provider name. This PR fixes that and refactors the initialization code a little to be cleaner and more uniform.
> Fix for provider initialization sequence in fluent constructor

- PetaPoco/Core/ConventionMapper.cs
I noticed while providing an example for #527 that the `IMapper` methods in `ConventionMapper` are not marked as virtual, which makes it harder to inherit from that class.
> Make ConventionMapper methods virtual

- PetaPoco/Core/ColumnInfo.cs
- PetaPoco/Core/ConventionMapper.cs
- PetaPoco/Core/TableInfo.cs
@pleb Interested in your thoughts on this. I noticed that while `StandardMapper` calls methods in `ColumnInfo` and `TableInfo` to get information, `ConventionMapper` duplicates that code and then adds a little extra processing (like inflection). I thought it would be good to refactor so that `ConventionMapper` can call the same base methods in `ColumnInfo` and `TableInfo` and then do what it needs to.
(One practical implication of the duplication is that when I added `IncludeInAutoSelect` to `ResultColumnAttribute`, I only handled it it `ConventionMapper`, because I didn't see the other methods. Now it's handled in `ColumnInfo` and picked up by both `ConventionMapper` and `StandardMapper`.)
The refactored methods are not as clean as I would like them – they've got a couple of `out` params …
> Refactor to get rid of duplicate TableInfo/ColumnInfo code

- PetaPoco.Tests.Integration/Databases/BaseQueryTests.cs
- PetaPoco/Utilities/PagingHelper.cs
A integration test to view the defect comment in this issue: #534
> Integration Test demonstrating defect generating sql Count

- PetaPoco/Utilities/PagingHelper.cs
Due to issue #548 , the @promatcloud proposes the following pull request:
Optimized performance of `RegexGroupBy` in `PagingHelper` class and inclusion of `SimpleRegexGroupBy` for use in `IsMatch` check.
> Optimized performance PagingHelper class 

- PetaPoco.Tests.Integration/Databases/MSSQL/MssqlPreExecuteTests.cs
- PetaPoco/Core/DatabaseProvider.cs
- PetaPoco/Database.cs
Relates to #562 
I started out just moving the call to `_provider.PreExecute()` into `Database.DoPreExecute()`, but then I saw that the usage pattern around calling that wasn't consistent either. I wound up consolidating the pattern in a few helper classes in `Database`.
I wasn't able to write unit tests to verify that `PreExecute()` always gets called because there were elements of the process that I couldn't figure out how to mock. So I did write a set of integration tests, which aren't really integration tests because they never use the database -- but the tests needed a live `Connection` to work with. They make use of a custom `DatabaseProvider` which records the parameters it sees and then throws an exception to abort the database action; this way the tests can verify that …
> Standardize calls to PreExecute

- PetaPoco.Tests.Unit/Core/EnumMapperTest.cs
- PetaPoco/Utilities/EnumMapper.cs
catches KeyNotFoundException and throws InvalidOperationException containing the invalid value and the Enum-Name in which the value should have been mapped.
> KeyNotFoundException with concise message

- PetaPoco.Tests.Unit/CreateCommandTests.cs
- PetaPoco/Database.cs
- PetaPoco/Properties/launchSettings.json
Relates to #562 
This was trivial to implement, but I'm not sure if we should actually do it. After looking at some more DataProviders, I see that most of them handle this kind of translation from .NET type to DbType themselves. The particular db I'm working with for some reason doesn't explicitly handle `byte[]`, which is why I was having problems. But if I can count on `DatabaseProvider.PreExecute()` being called (see other PR), then I can handle this myself in my custom `DatabaseProvider`.
So I'm perfectly fine if you want to decline this PR.
> Force byte[] params to map to DbType.Binary

- PetaPoco/Core/PocoData.cs
Proposed fix for issue I submitted earlier today [https://github.com/CollaboratingPlatypus/PetaPoco/issues/285](url)
This is pretty straight forward just adds explicit conversion from Guid to string. Guid does not implement IConvertible so the else clause currently results in an exception. This is mostly applicable to Sql Server where uniqueidentifiers are mapped to guids by SqlClient but are often much easier to treat as strings.
> Fix for guid to string conversion issue; #285

- PetaPoco.Tests.Unit/Core/AnsiStringTests.cs
- PetaPoco/Core/AnsiString.cs
- PetaPoco/Core/AnsiStringExtensions.cs
I'm working with some databases that use `varchar` instead of `nvarchar`, and I've been finding it awkward to have to use `new AnsiString("foo")` to define parameters in order to force `DbType.AnsiString`. I thought it would be helpful to add some alternate syntaxes.
These are all equivalent:
```csharp
var newObject = new AnsiString("foo");  // existing
var explicitCast = (AnsiString)"bar";   // new -- can only cast strings
var extensionMethod = "baz".ToAnsiString();    // new -- works on any object, just like ToString()
```
> Add some syntactic sugar to AnsiString

- PetaPoco.Tests.Integration/Databases/BaseQueryTests.cs
- PetaPoco/Core/MultiPocoFactory.cs
Partly addresses the problem raised in https://github.com/CollaboratingPlatypus/PetaPoco/issues/617
This will ensure cached poco factories are only used if the number of columns returned by the query has not been changed. This is not foolproof, as columns may have been added to one table and removed from another, but it seems like a worthwhile improvement.
NB: I only have SQLite on my local machine, so would appreciate it if someone could fix the test to work with other databases if necessary.
> Improve resilience of MultiPoco queries to database schema changes

- PetaPoco/Core/PocoData.cs
- PetaPoco/Database.cs
Add alternate non-IL Factory method to PocoData.cs. This is usable under iOS (under Xamarin), which blocks IL generation and some reflection operations.
These changes are a first iteration. They are tested on iOS, but use only the commonly used PetaPoco features.
Because the error is runtime and not compile time, we may wish to add a configuration option to allow use with either code path. This depends on if the non-iOS compatible path yields significant performance improvements (I would imagine this is why it was moved to IL).
Also, MultiPocoFactory.cs has a CreateMultiPocoFactory method (and perhaps GetAutoMapper) which would need to be converted for complete coverage. I've never used the MultiPoco feature before and thought I'd test the waters as to how essential that is before I leap …
> iOS compatibility changes

- PetaPoco.Tests.Unit/Utilities/ParametersHelperTests.cs
- PetaPoco/Utilities/ParametersHelper.cs
We can currently pass in POCOs that hold parameter values (for queries and stored procs) and PP will turn them into arrays of parameters. This PR lets us pass in Dictionaries as well.
```c#
db.Query(sql, new { Foo = 5, Bar = "apple" });
// same as 
var dict = new Dictionary<string, object>()
{
["Foo"] = 5,
["Bar"] = "apple"
}
db.Query(sql, dict);
```
The reason for this is that it lets you build up a collection of arbitrarily named parameters.
> Allow dictionaries to be passed with parameters

- PetaPoco.Tests.Unit/Utilities/ParametersHelperTests.cs
- PetaPoco/Utilities/ParametersHelper.cs
In `IDictionary`, `dict[item]` returns null if the key doesn't exist, which is different behavior from the generic `IDictionary<TKey, TValue>`. We want to separate the check for the key from retrieving the value, because we do want to allow through null values -- as we currently do with object properties. (They're converted to `DBNull.Value` in `Database.SetParameterValues()`.
> Allow null values in dictionaries

- PetaPoco/Attributes/ColumnAttribute.cs
- PetaPoco/Core/ColumnInfo.cs
- PetaPoco/Core/DateTime2.cs
- PetaPoco/Core/DateTime2Extensions.cs
- PetaPoco/Core/DateTime2Extentions.cs
- PetaPoco/Core/PocoColumn.cs
- PetaPoco/Core/PocoData.cs
- PetaPoco/Database.cs
- PetaPoco/Utilities/ParametersHelper.cs
the normal AnsiString fix is fine for Fetch<> ...
var test = db.FirstOrDefault<TABLE>("where NAME = @0", new AnsiString("YOURNAME"));
but for Update and Insert i cant use AnsiString 
test.SOMEDATETIME2COLUMN = DateTime.Now();
test.SOMESTRINGCOLUMN = "Hello";
test.Update() 
my new model looks like this
[Column("SOMEDATETIME2COLUMN", IsDateTime2 = true)] public DateTime? SOMEDATETIME2COLUMN { get; set;}
[Column("SOMESTRINGCOLUMN", IsAnsi = true)] public string SOMESTRINGCOLUMN { get; set;}
> ansi and datetime2 fix

- PetaPoco.Tests.Unit/Utilities/ParametersHelperTests.cs
- PetaPoco/PetaPoco.csproj
*   Many current dev machines (including mine) don't have net40 reference assemblies installed, and it's no longer possible to obtain them. Including a design-time NuGet package allows things to compile.
*   The PR for DateTime2 updated the signature on `ParametersHelper.ProcessStoredProcParams()` but did not update the corresponding unit test.
> Fix unit test

- PetaPoco.Tests.Unit/Core/ConventionMapperTests.cs
- PetaPoco.Tests.Unit/Core/PocoDataTests.cs
- PetaPoco.Tests.Unit/Models/ParentChildClasses.cs
- PetaPoco.Tests.Unit/Utilities/ParametersHelperTests.cs
- PetaPoco/Core/ColumnInfo.cs
- PetaPoco/Core/ConventionMapper.cs
- PetaPoco/PetaPoco.csproj
Fixes #640 
I verified that the tests (specifically Parent2/Child2) failed with the current code and pass after this change.
I wound up using `Attribute.GetCustomAttributes()` because the overload I wanted of `pi.GetCustomAttributes()` doesn't exist in net40.
> Fix calls to GetCustomAttributes()

- PetaPoco.Tests.Unit/CreateParameterTests.cs
- PetaPoco.Tests.Unit/DatabaseConfigurationTests.cs
- PetaPoco/Database.cs
Better late than never!
Closes #122 
@pleb The existing `CreateCommand()` methods only appear on `Database`, not in any of the implemented interfaces, so I did the same with `CreateParameter()`.
> Add Database.CreateParameter()

- PetaPoco/PetaPoco.csproj
This appears to be my fault -- when I was doing some work to add a .net standard 2.1 target, it looks like I screwed up the dependency on ReferenceAssemblies. It should only be a build-time dependency, but it was getting linked in to the NuGet package. No harm, just some files dragged in that shouldn't be.
> Fix ReferenceAssemblies dependency

- LICENSE.txt
Reverts `LICENSE.txt` to it's former state. See https://github.com/CollaboratingPlatypus/PetaPoco/issues/678#issuecomment-1580604377t from @asherber.
> Revert license copyright date change from commit 7f4eb8db

- PetaPoco/Database.cs
As per https://github.com/CollaboratingPlatypus/PetaPoco/issues/675, autoincrement column names should be escaped.
> 675 when inserting name of autoincrement column with expression is not escaped

- PetaPoco.Tests.Integration/Databases/BaseDatabaseTests.cs
- PetaPoco/Database.cs
Added tests for event invocation when opening shared connection with both synchronous and asynchronous methods. `BaseDatabaseTests.OpenSharedConnectionAsync_WhenCalled_ShouldInvokeOnConnectionOpening()` fails on this initial commit. The commit following this fixes `Database.OpenSharedConnectionAsync(CancellationToken)` to call `OnConnectionOpening` as the synchronous counterpart does, and results in a passing test.
I'll add tests for the remaining events shortly for completeness' sake.
closes #685
> bugfix: OpenSharedConnectionAsync fails to invoke OnConnectionOpening

- LICENSE.txt
- PetaPoco.Tests.Integration/Databases/BaseUpdateTests.cs
- PetaPoco/Database.cs
The exception occurs when passing in the PocoColumn to the `AddParam` method. As I mentioned in the linked issue thread, this is fine for statically typed POCO objects, but for dynamic or anonymous types, there is no underlying compile-time PropertyInfo for that column (property).
Changing the null check from `if (pc != null)` to `if (pc != null && pc.PropertyInfo != null)` fixes the problem, but I'm not convinced this is the ideal resolution, since the method is specifically designed to accept a null value for the third parameter (for dynamic and anonymous types), and likely there are other bugs related to dynamic that would share the same root cause as this one, somewhere farther down the call path.
https://github.com/CollaboratingPlatypus/PetaPoco/blob/34ff2900ec72d5cae863d4b04f7d87bcc4 …
> Fix NullReferenceException thrown when executing operations with `dynamic` POCOs

- PetaPoco.Tests.Integration/Databases/OracleTests/OracleQueryTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleStoredProcTests.cs
- PetaPoco.Tests.Integration/Databases/QueryTests.cs
- PetaPoco.Tests.Integration/Providers/OracleTestProvider.cs
- PetaPoco.Tests.Integration/Scripts/OracleBuildDatabase.sql
- PetaPoco.Tests.Integration/Scripts/OracleSetupDatabase.sql
- PetaPoco.Tests.Unit/Utilities/PagingHelperTests.cs
- PetaPoco/Database.cs
- PetaPoco/Providers/OracleDatabaseProvider.cs
- PetaPoco/Utilities/PagingHelper.cs
Would've like to separate the core changes into a different PR, but got ahead of myself.
> Fix some more failing integration tests

- PetaPoco/Core/PocoData.cs
- PetaPoco/Database.cs
Include Mapper Type in cache key for PocoData. Fixes #517.
Avoid "duplicate key" side effect in `PocoData.ForObject` method when handling dynamic objects.
> Fix PocoData Cache Issue

- PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj
Npgsql has a high-severity vulnerability, which they take seriously enough to issue new builds of out-of-support versions. It doesn't matter that much for this project, since the dependency is only in the integration tests project, but merging this will make Dependabot happy.
As a side note, it would probably be a good idea to go through the test projects and update frameworks and libraries to more recent versions. I can take a look at this if I can get the Docker stuff running on my new machine.
> Update Npgsql to v4.1.13

- PetaPoco.Tests.Integration/Databases/OracleTests/OracleDatabaseTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleDeleteTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleExecuteTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleInsertTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleMiscellaneousTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OraclePreExecuteTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleQueryLinqTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleQueryTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleStoredProcTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleTriageTests.cs
- PetaPoco.Tests.Integration/Databases/OracleTests/OracleUpdateTests.cs
- PetaPoco.Tests.Integration/Databases/UpdateTests.cs
- PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj
- PetaPoco.Tests.Integration/Providers/OracleTestProvider.cs
- PetaPoco.Tests.Integration/Scripts/OracleBuildDatabaseDelimited.sql
- PetaPoco.Tests.Integration/Scripts/OracleBuildDatabaseOrdinary.sql
- PetaPoco.Tests.Integration/Scripts/OracleSetupDatabaseDelimited.sql
- PetaPoco.Tests.Integration/Scripts/OracleSetupDatabaseOrdinary.sql
- PetaPoco.Tests.Integration/app.config
- PetaPoco.Tests.Integration/appsettings.json
- PetaPoco/Database.cs
- PetaPoco/Providers/OracleDatabaseProvider.cs
- PetaPoco/Utilities/ParametersHelper.cs
- Scripts/Startup/oracle.sql
- docker-compose.yml
Test Oracle Delimited and Ordinary Identifiers Separately.
Split Oracle DB scripts, connection strings and tests in two.
One set of tests to use PP OOTB (Delimited) and one set of tests to use PP with Custom provider and mapper (Ordinary).
Fix Oracle setup script. Wait for tablespace drop operation to complete before creating the new tablespace.
**Database.cs**
- Escape Oracle Stored Procedure parameter names instead of ensuring paramater prefix.
**OracleDatabaseProvider.cs**
- Quote identifier when escaping (no Regex or ToUpperInvariant).
- Disable statement caching for Oracle client.
> Fix remaining failing integration tests
