CollaboratingPlatypus/PetaPoco

README.markdown
Change the link to https://github.com/robconery/massive
=> Fix broken link to Rob Conery's Massive

PetaPoco/Attributes/ColumnAttribute.cs, PetaPoco/Attributes/ExplicitColumnsAttribute.cs, PetaPoco/Attributes/IgnoreAttribute.cs, PetaPoco/Attributes/PrimaryKeyAttribute.cs, PetaPoco/Attributes/ResultColumnAttribute.cs, PetaPoco/Attributes/TableNameAttribute.cs, PetaPoco/Core/ConventionMapper.cs
Minor bug fix and updates to documentation
=> Pulls development version

PetaPoco.Tests.Unit/Core/SqlTests.cs, PetaPoco/Core/Sql.cs
add `Set` clause support in Sql class in `Sql` class that is almost the same like how to use `Where`
=> add Set clause support in Sql class

PetaPoco.Tests.Integration/Databases/BaseQueryTests.cs, PetaPoco.Tests.Integration/Databases/MSSQL/MssqlQueryTests.cs, PetaPoco.Tests.Integration/Models/Order.cs, PetaPoco.Tests.Integration/Models/OrderLine.cs, PetaPoco/Core/GridReader.cs, PetaPoco/Core/IGridReader.cs, PetaPoco/Database.cs, PetaPoco/IQuery.cs, PetaPoco/PetaPoco.csproj
Support for Sql query results with multiple results sets.
Simple/limited integration tests provided
=> Multi result-set support

PetaPoco/Core/DatabaseProvider.cs
Please look at this 
https://github.com/CollaboratingPlatypus/PetaPoco/pull/299/files#diff-5b7a40677b91f6333c40fa75ad9d2193L237
and this
https://github.com/CollaboratingPlatypus/PetaPoco/pull/299/files#diff-5b7a40677b91f6333c40fa75ad9d2193L195
=> Remove duplicate conditions.

PetaPoco/T4 Templates/Database.tt, PetaPoco/T4 Templates/PetaPoco.Core.ttinclude, PetaPoco/T4 Templates/PetaPoco.Generator.ttinclude
Another patch, this adds a ExplicitColumns option defaulting to on to maintain the current functionality.  If toggled off then the ExplicitColumns attribute is removed and Column attributes only added if the property name and column name don't match.
=> Pynej patch 2

PetaPoco/Core/DatabaseProvider.cs, PetaPoco/Providers/OracleDatabaseProvider.cs
I working with PetaPoco in my project, this project using Oracle.DataAccess.dll for connection to Oracle DB, I fixed for the error under this situation.
=> Situation for OracleConnection when using the Oracle.DataAccess.dll

PetaPoco/T4 Templates/PetaPoco.Core.ttinclude
Reverts CollaboratingPlatypus/PetaPoco#365
Due to bug #392
=> Revert "Allow transformation of T4 template outside of Visual Studio"

PetaPoco/Database.cs
- this constr     public Database(IDbConnection connection)
- becomes this public Database(IDbConnection connection, IMapper defaultMapper = null)
=> Add ability to set a default mapper in constr

PetaPoco.Tests.Unit/DatabaseTests.cs, PetaPoco/Database.cs
Not sure if this desirable, since I don't know what kind of table would have a decimal PK, but I don't think it would do any harm.
Closes #466
=> Teach IsNew() about decimal primary key

PetaPoco.Tests.Unit/Core/SqlTests.cs, PetaPoco/Core/Sql.cs
I'm not sure how you feel about this. It helps with the issue in #488, but it may be unnecessary or may lead to confusion or misuse. I don't feel strongly about arguing for its inclusion.
=> Allow for an IDbDataParameter to be added directly to Sql

PetaPoco.Tests.Integration/AppSetting.cs, PetaPoco.Tests.Integration/Databases/BaseDatabase.cs, PetaPoco.Tests.Integration/Databases/BaseDatabaseTests.cs, PetaPoco.Tests.Integration/Databases/DBTestProvider.cs, PetaPoco.Tests.Integration/Databases/Firebird/FirebirdDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MSAccess/MsAccessDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MSSQL/MssqlDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MSSQLCe/MssqlCeDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MariaDb/MariaDbDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MySQL/MySqlDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/Postgres/PostgresDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/Sqlite/SqliteDBTestProvider.cs
=> Fix broken integration test

PetaPoco.Tests.Unit/Core/MapperTest.cs, PetaPoco/Core/Mappers.cs
#Issue
link https://github.com/CollaboratingPlatypus/PetaPoco/issues/540
=> fix(#540): Mapper register method throw ArgumentException

PetaPoco.Tests.Integration/Databases/BaseUpdateTests.cs, PetaPoco.Tests.Unit/DatabaseTests.cs, PetaPoco/Database.cs
Fixes #551 
@pleb I can also backport the changes to v5 if you want.
=> Update should return 0 when columns is empty

PetaPoco/Database.cs
=> Check AnsiString.Value for null

PetaPoco/Core/PocoData.cs
=> Expose PocoData.FlushCaches method

PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorDBTestProvider.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorDatabaseTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorDeleteTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorExecuteTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorInsertTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorMiscellaneousTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorQueryLinqTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorQueryTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorStoredProcTests.cs, PetaPoco.Tests.Integration/Databases/MySQLConnector/MySqlConnectorUpdateTests.cs, PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj, PetaPoco.Tests.Integration/app.config, PetaPoco.Tests.Integration/appsettings.json, PetaPoco/Core/DatabaseProvider.cs, PetaPoco/Providers/MySqlConnectorDatabaseProvider.cs, docker-compose.yml
=> Adds support for MySqlConnector

README.markdown
Found a slight misspelling of the package name in the readme.
=> Fixes package name in readme

PetaPoco/Database.cs, PetaPoco/PetaPoco.csproj
Closes #628 
@pleb I did not add tests yet. Please feel free to do so if you have time (you are able to commit to this branch); otherwise, I'll try to get to it next couple of days.
Note that VS2022 will not compile projects that target net40. I only have VS2022 on my machine now, so in order to compile locally I just delete that target (but don't commit that change to git).
=> Async transaction support

PetaPoco.Tests.Unit/DatabaseConfigurationTests.cs, PetaPoco/Database.cs, PetaPoco/DatabaseConfigurationExtensions.cs
=> Adds a hook to allow connection modification before open is called

PetaPoco/Database.cs
=> Ensure db command is disposed

PetaPoco.Tests.Integration/Databases/BaseQueryTests.cs
=> fix breaking syntax error in multipoco test

PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj, PetaPoco.Tests.Unit/PetaPoco.Tests.Unit.csproj
Updated 2 libs in the test projects to satisfy Dependabot.
=> Fix Dependabot alerts

PetaPoco.Tests.Integration/Databases/BaseQueryTests.cs, PetaPoco.Tests.Integration/Databases/MySQL/MySqlQueryTests.cs, PetaPoco.Tests.Integration/Models/ReadOnlyPoco.cs, PetaPoco.Tests.Integration/Scripts/MySqlBuildDatabase.sql, PetaPoco/Core/MultiPocoFactory.cs, PetaPoco/Core/PocoData.cs
=> add null check for property `Set` method

PetaPoco/Core/IProvider.cs, PetaPoco/Database.cs, PetaPoco/IConnection.cs, PetaPoco/IQueryAsync.cs, PetaPoco/PetaPoco.csproj
This should fix #680, based on [this StackOverflow answer](https://stackoverflow.com/a/48664173).
=> Add GenerateDocumentationFile element to csproj

.github/workflow/pr.yml, appveyor.yml
~~Untested, but this should resolve~~ fixes the nuget source error causing appveyor builds to fail on development branch.
=> fix: ci/cd workflow build error

PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj, PetaPoco.Tests.Unit/PetaPoco.Tests.Unit.csproj
- Fixes a build warning regarding duplicate project references with System.Data.SqlClient
- Adds an exclusive max version for Moq package reference
closes #688
=> Tests project file updates

PetaPoco.Tests.Integration/PetaPoco.Tests.Integration.csproj, PetaPoco.Tests.Unit/PetaPoco.Tests.Unit.csproj
All 6053 tests pass on both targets (net472 and netcoreapp3.1).
closes Upgrade tests projects target framework to net472,netcoreapp3.1 #703
=> Upgrade target frameworks to net472,dotnetcore3.1 (tests)

T4Templates/Database.tt, T4Templates/PetaPoco.Core.ttinclude, T4Templates/PetaPoco.Generator.ttinclude
Normalize whitespace and code formatting.
Add support for SQLite.
Closes #503
=> Fix WhiteSpace Issue in File Generated by T4 Template
